### ISSUE TITLE
Как задеплоить образ, который собирается из вложенного проекта репозитория?

### ISSUE THREAD

**Issue by navff** [nikolaymatrosov/yc-cr-github-action#1]
Структура проекта:
/
--Admin.Web
-----Dockerfile
--Public.WebStore
-----Dockerfile
--Common

При попытке деплоя гитхаб не может найти Dockerfile. Похоже, что нужно что-то предпринять из-за вложенности. 
```unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/runner/work/anyor/anyor/Dockerfile: no such file or directory```

Action:
```
name: Admin.Web.Docker.Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    # that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE,
        # so your job can access it
        - uses: actions/checkout@v2
        - name: Login to Yandex Cloud Container Registry
          id: login-cr
          uses: yc-actions/yc-cr-login@v1
          with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
            path: Admin.Web

        - name: Build, tag, and push image to Yandex Cloud Container Registry
          env:
            CR_REGISTRY: XXXXX
            CR_REPOSITORY: containers-registry
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t cr.yandex/XXXXX/adminweb:latest .
            docker push     cr.yandex/XXXXX/adminweb:latest
```
![dunrOV7](https://user-images.githubusercontent.com/869492/180636897-541bc4d2-7737-4269-9a2b-a66a115f2277.png)
